name: virgin_sk
dataset:
  root: ../data
  num_sample_geo: 2048
  sigma_geo: 0.05
  num_verts: 2048
  sk_ratio: 5.0

learning_rate: 1e-3 
batch_size: 24
num_threads: 24

# ckpt_path: ../data/checkpoints/virgin/ckpt_13.pth
resume: False
overfit: False

momentum: 0.5 
optim: Adam

num_epoch: 20
freq_eval: 1000
freq_plot: 10
freq_show: 200
freq_save: 500
schedule: [3, 10, 18]