name: NASA_pl_fast_dev
dataset:
  root: ../data
  num_sample_geo: 2048
  sigma_geo: 0.05
  num_verts: 2048
  sk_ratio: 0.5
  train_bsize: 0.001
  val_bsize: 0.006
  test_bsize: 0.01

learning_rate: 1e-5
batch_size: 20
num_threads: 12

ckpt_path: "../data/checkpoints/NASA_w_sk/top_k_epoch=9.ckpt"
overfit: 0
resume: False
test_mode: False
fast_dev: False

momentum: 0.5 
optim: SGD

num_epoch: 1
freq_eval: 4
freq_plot: 2
freq_show: 2
freq_save: 2
schedule: [1]