name: NASA_pl_fast_dev
dataset:
  root: ../data
  num_sample_geo: 2048
  sigma_geo: 0.05
  num_verts: 2048
  sk_ratio: 0.5
  train_bsize: 0.002
  val_bsize: 0.01
  test_bsize: 0.1

learning_rate: 1e-5
batch_size: 24
num_threads: 24

ckpt_path: ""
overfit: 0
resume: True
test_mode: False
fast_dev: False

momentum: 0.5 
optim: SGD

num_epoch: 3
freq_eval: 2
freq_plot: 2
freq_show: 2
freq_save: 2
schedule: [1]